# 
# SPDX-License-Identifier: MIT
# 
# Copyright (c) 2025 Andrew Ellis Page
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 

        
name: UCompleter

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: rust:latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - run:  rustup update
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test && cd aep_rust_common && cargo test
    - name: rustup aarch64
      run: rustup target add aarch64-unknown-linux-gnu
    - name: gcc-arm64
      run:  apt-get update && apt-get install -y gcc-aarch64-linux-gnu
    - name: aarch64
      run: cargo build --target=aarch64-unknown-linux-gnu 
    - name: deb aarch64
      run: cargo deb --target=aarch64-unknown-linux-gnu 
    - name: deb amd64
      run: cargo deb
    - uses: actions/upload-artifact@v4
      with:
        name: ucompleter-arm64
        path: "target/aarch64-unknown-linux-gnu/debian/ucompleter*.deb"
        overwrite: true
    - uses: actions/upload-artifact@v4
      with:
          name: ucompleter-x86
          path: target/debian/ucompleter*.deb
          overwrite: true
          
